[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:cron]
command=/usr/sbin/cron -f
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/cron.log
stderr_logfile=/var/log/supervisor/cron_err.log

[program:httpserver]
command=python -m http.server 80 --directory /app/site
directory=/app/site
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/httpserver.log
stderr_logfile=/var/log/supervisor/httpserver_err.log
